version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: tutor-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${HOST_DB_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  flyway:
    image: flyway/flyway:latest
    container_name: tutor-flyway
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    # Run migrations when invoked as: `docker compose run --rm flyway migrate`
    entrypoint: ["flyway"]
    working_dir: /flyway
